version: "3.4"
services:
  db:
    image: pgvector/pgvector:pg15
    container_name: pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-main}
      POSTGRES_USER: ${POSTGRES_USER:-testuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - ./sqls/create:/docker-entrypoint-initdb.d/create
      - ./sqls/insert:/docker-entrypoint-initdb.d/insert
      - ./sqls/execute_all_sql.sh:/docker-entrypoint-initdb.d/execute_all_sql.sh
    restart: always

networks:
  app_network:
    driver: bridge
